baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'

[module]
#replacements = 'github.com/regisphilibert/hugo-module-icons -> ..\..\hugo-module-icons'
[[module.imports]]
path = 'github.com/regisphilibert/hugo-module-icons'